<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="J Steven Raquel" />


<title>Modeling human serum albumin’s association with survival among end-stage renal disease patients</title>

<script src="site_libs/header-attrs-2.25/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link rel="apple-touch-icon" sizes="57x57" href="icons/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="icons/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="icons/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="icons/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="icons/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="icons/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="icons/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="icons/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="icons/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="icons/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="icons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="icons/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="icons/favicon-16x16.png">
<link rel="manifest" href="manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="icons/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    background-color: #232629;
    color: #7a7c7d;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #7a7c7d;  padding-left: 4px; }
div.sourceCode
  { color: #cfcfc2; background-color: #232629; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span { color: #cfcfc2; } /* Normal */
code span.al { color: #95da4c; background-color: #4d1f24; font-weight: bold; } /* Alert */
code span.an { color: #3f8058; } /* Annotation */
code span.at { color: #2980b9; } /* Attribute */
code span.bn { color: #f67400; } /* BaseN */
code span.bu { color: #7f8c8d; } /* BuiltIn */
code span.cf { color: #fdbc4b; font-weight: bold; } /* ControlFlow */
code span.ch { color: #3daee9; } /* Char */
code span.cn { color: #27aeae; font-weight: bold; } /* Constant */
code span.co { color: #7a7c7d; } /* Comment */
code span.cv { color: #7f8c8d; } /* CommentVar */
code span.do { color: #a43340; } /* Documentation */
code span.dt { color: #2980b9; } /* DataType */
code span.dv { color: #f67400; } /* DecVal */
code span.er { color: #da4453; text-decoration: underline; } /* Error */
code span.ex { color: #0099ff; font-weight: bold; } /* Extension */
code span.fl { color: #f67400; } /* Float */
code span.fu { color: #8e44ad; } /* Function */
code span.im { color: #27ae60; } /* Import */
code span.in { color: #c45b00; } /* Information */
code span.kw { color: #cfcfc2; font-weight: bold; } /* Keyword */
code span.op { color: #cfcfc2; } /* Operator */
code span.ot { color: #27ae60; } /* Other */
code span.pp { color: #27ae60; } /* Preprocessor */
code span.re { color: #2980b9; background-color: #153042; } /* RegionMarker */
code span.sc { color: #3daee9; } /* SpecialChar */
code span.ss { color: #da4453; } /* SpecialString */
code span.st { color: #f44f4f; } /* String */
code span.va { color: #27aeae; } /* Variable */
code span.vs { color: #da4453; } /* VerbatimString */
code span.wa { color: #da4453; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="about_me.html">About Me</a>
</li>
<li>
  <a href="resume.html">Resume</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Projects
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="esrd-survival.html">Survival analysis of kidney disease patients</a>
    </li>
    <li>
      <a href="matern-spatial.html">Spatial modeling of school gun violence</a>
    </li>
    <li>
      <a href="ergm_models.html">Sexual network exponential random graph modeling</a>
    </li>
    <li>
      <a href="wine-classification.html">Classifying wine quality</a>
    </li>
    <li>
      <a href="bitcoin.html">Forecasting bitcoin value</a>
    </li>
    <li>
      <a href="housing-prices.html">Predicting housing prices</a>
    </li>
    <li>
      <a href="ggomoku.html">Play Gomoku using Shiny</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Contact Me
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="mailto:jsteven.raquel8@gmail.com">jsteven.raquel8@gmail.com</a>
    </li>
    <li>
      <a href="https://github.com/jstevenr">GitHub</a>
    </li>
    <li>
      <a href="https://www.linkedin.com/in/jstevenr/">LinkedIn</a>
    </li>
    <li>
      <a href="https://twitter.com/jsteven_r/">Twitter</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Modeling human serum albumin’s association
with survival among end-stage renal disease patients</h1>
<h4 class="author">J Steven Raquel</h4>

</div>


<div id="abstract" class="section level1">
<h1>Abstract</h1>
<p>In this study, we looked at data from 1979 hemodialysis patients in
order to determine the risk factors for end-stage renal disease (ESRD),
a condition which affects more than 850,000 individuals in the United
States alone. Serum albumin, a blood protein which contributes to
calcium levels in plasma, was recorded both at their entry into the
study and at several follow-up periods throughout their time in their
study. The model in which we treated albumin as static based on the
subject’s albumin level at the time of their entry into the study gave a
coefficient estimate for albumin as <span
class="math inline">\(\exp(\hat \beta_1) \approx 0.649\)</span> (95% CI:
<span class="math inline">\([0.530, 0.818]\)</span>, p-value: <span
class="math inline">\(\approx 0.00016\)</span>). The model in which we
also treated albumin as static based on its value at baseline, but
included along with it an interaction term based on the subject’s
history of cardiovascular disease (or lack thereof), gave a coefficient
estimate for albumin as <span class="math inline">\(\exp(\hat \beta_1)
\approx 0.491\)</span> (95% CI: <span class="math inline">\([0.329,
0.732]\)</span>, p-value: <span class="math inline">\(0.0005\)</span>),
and a coefficient estimate for the interaction term as <span
class="math inline">\(\exp(\hat \beta_9) \approx 1.540\)</span> (95% CI:
<span class="math inline">\([0.964, 2.459]\)</span>, p-value: <span
class="math inline">\(\approx 0.071\)</span>). The model in which we
treated albumin as a time-varying covariate based on the subject’s
albumin levels as recorded throughout their time in the study (with no
interaction), gave a coefficient estimate for albumin as <span
class="math inline">\(\exp(\hat \beta_1) \approx 0.549\)</span> (95% CI:
<span class="math inline">\([0.485, 0.626]\)</span>, p-value: <span
class="math inline">\(\approx 0\)</span>). Finally, the model in which
we treated album as a time-varying covariate as well as included an
interaction term gave the respective estimates as <span
class="math inline">\(\exp( \hat \beta_1) \approx 0.369\)</span> (95%
CI: <span class="math inline">\([0.290, 0.469]\)</span>) for albumin,
and <span class="math inline">\(\exp (\hat \beta_9) \approx
1.738\)</span> (95% CI: <span class="math inline">\([1.316,
2.295]\)</span>) for the interaction term. All models included race,
whether the subject appeared undernourished, cholesterol, age, and
diabetes as predictor variables, while treating body mass index and
smoking history as confounding variables.</p>
</div>
<div id="background-introduction" class="section level1">
<h1>Background / Introduction</h1>
<p>End stage renal disease (ESRD) is a dangerous condition in which an
individual’s kidneys no longer adequately perform their function of
filtering out toxins, and affects over 850 thousand individuals in the
US alone. While most individuals who suffer from ESRD would ideally like
to receive a kidney transplant, the other option is hemodialysis, which
effectively performs the same function as one’s kidneys.</p>
<p>In the past it has been posited that protein biomarkers such as serum
albumin may have an association with risk of death amongst hemodialysis
patients, as human serum albumin is crucial in maintaining body
nutrition, as it regulates the fluid exchange between various body
parts, including blood circulation to the kidneys (Ha 2013). It also
plays a role in metabolism. As such, it stands to reason that a lack of
serum albumin would be linked with mortality among hemodialysis
patients, whose kidneys are performing under below standards of
healthiness.</p>
<p>To test this hypothesis formally, this study was conducted based off
of a sample of N = 1979 hemodialysis patients across the US who had
undergone dialysis in December 2014. For all patients, serum albumin
levels were recorded at the time of entry into the study, along with
other demographic records including age, race, gender, body mass index
(BMI), smoking history, a subjective assessment of nutritional status.
Laboratory measurements on cholesterol, serum triglyceride, and
post-dialysis systolic blood pressure measurements were also included.
Serum albumin levels were also recorded repeatedly over time throughout
the study, with records spaced between 1 to 2 months apart.</p>
</div>
<div id="methods" class="section level1">
<h1>Methods</h1>
<div id="the-data" class="section level2">
<h2>The Data</h2>
<p>Our data consists of 1979 hemodialysis patients who were undergoing
dialysis in December 2014 in dialysis clinics across the US. These
patients’ respective demographics vary across gender, race, as well as
health history including body mass index (BMI), smoking history, history
of cardiovascular disease (CVD), and diabetes. Measurements of
nutritional status, such as levels of cholesterol, serum albumin, serum
triglycerides, and post-dialysis systolic blood pressure were also
recorded. Albumin, itself known to be a measure of healthiness on
account of its role in filtering toxins from the body, was recorded
consistently at periods between one to two months apart from one
another, starting at the subject’s entry into the study. Other variables
recorded were a measure of the amount of time the subject had been
affected by ESRD before entering the study, as well as an indicator for
whether the study nurse noted the subject in question appeared
undernourished at the time of data collection.</p>
<p>While the sampling scheme is relatively sound in that we have a large
random sample, one of the shortcoming of the study design is that there
are also a large amount of missing records for certain variables,
particularly serum triglycerides, which was missing in over 20% of
records. It’s also notable that we do not have clear information on the
exact dates between albumin measurements, so we cannot state
conclusively that two different subjects with similar serum albumin
levels two time periods after baseline had the same amount of time
between collections.</p>
<p>There are a number of ties–moments in time where more than one
individual died–in the data. The method we used to account for this when
fitting the model is the Efron approximation. A variety of different
methodologies exist to deal with ties in survival analysis, but the
Efron approximation offers a solid middle ground between the average
partial likelihood and the decidedly inaccurate Breslow approximation,
by weighting the partial likelihood by taking the average weight of the
failures at time <span class="math inline">\(t_j\)</span>.</p>
</div>
<div id="confounders-and-missing-data" class="section level2">
<h2>Confounders and Missing Data</h2>
<p><em>Confounding variables</em>, or confounders, are variables which
are causally associated with the predictor of interest and causally
associated to the outcome of interest. Failing to account for
confounders results in biased analyses and potentially misleading
results. We tested formally for confounding variables first by following
known causal pathways e.g. being overweight/obese is a risk factor for
diabetes, so we suspected high BMI to be causally related to diabetes,
knowing both are a risk factor for death. Then we conducted log-rank
tests and Chi-squared tests for independence, establishing relationships
between the outcome (death) and the predictor in question.</p>
<p>We know a priori that smoking is associated with diabetes, which
itself is associated with a higher risk of mortality. Nicotine and other
chemicals in cigarettes affects insulin production, which can cause
diabetes. Additionally, a high BMI (i.e. being overweight or obese) is a
known risk factor for both death and diabetes. Both smoking and an
unhealthy BMI are associated with a higher risk of mortality relative to
non-smoking and a healthy BMI, hence we believe both of these variables
make for potential confounders in our model. We were able to support
these results through conducting individual log-rank tests both with and
without stratifying on the respective confounder.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="co"># smoking </span></span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a>lr1 <span class="ot">&lt;-</span> <span class="fu">survdiff</span>(<span class="fu">Surv</span>(tdeath, death) <span class="sc">~</span> diabetes, <span class="at">data =</span> usrds) <span class="co"># fail to reject H0</span></span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a>lr2 <span class="ot">&lt;-</span> <span class="fu">survdiff</span>(<span class="fu">Surv</span>(tdeath, death) <span class="sc">~</span> diabetes <span class="sc">+</span> <span class="fu">strata</span>(smokegrp), <span class="at">data =</span> usrds) <span class="co"># reject H0</span></span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a>lr3 <span class="ot">&lt;-</span> <span class="fu">survdiff</span>(<span class="fu">Surv</span>(tdeath, death) <span class="sc">~</span> diabetes <span class="sc">+</span> <span class="fu">strata</span>(bmi_grp), <span class="at">data =</span> usrds) <span class="co"># reject H0</span></span></code></pre></div>
<p>Other potential confounders which we do not have data on but may
still be relevant in terms of the research question are variables such
as a history of drug use or a history of alcohol use. Alcohol and drug
use have an adverse effect on the cardiovascular system (Gardner 2015),
and poor heart health is associated with increased risk of
mortality.</p>
<p>Also, of the 1979 subjects in the data, only 490 subjects had the
failure event (death), while the remainder were <em>censored</em>, which
is to say that they exited the study for reasons apart from the failure
event, e.g. withdrawal, relocation, etc. We aren’t explicitly aware of
the circumstances of the censorship within this context, but one should
be aware of the implications of censorship of results. One possible such
reason for censoring is that the patient received a kidney transplant,
recovered from ESRD, and longer needed to undergo dialysis, and exited
the study as a result. These particular instances of censoring are
considered right censoring.</p>
</div>
<div id="the-kaplan-meier-estimator" class="section level2">
<h2>The Kaplan-Meier estimator</h2>
<p>The first method used to quantify survival probability in survival
analysis is the non-parametric Kaplan-Meier estimator. It is based on
time <span class="math inline">\(t_i\)</span>, where <span
class="math inline">\(i = 1, ..., N\)</span>, for <span
class="math inline">\(N\)</span> time periods, <span
class="math inline">\(d_i\)</span>, the number of deaths at time <span
class="math inline">\(t\)</span>, and finally, <span
class="math inline">\(n\)</span>, the number of individuals at risk at
time <span class="math inline">\(t\)</span>. The group of individuals at
risk, otherwise known as the risk set, are comprised of all individuals
by that time point who have not experienced either the event of interest
(death), were censored.</p>
<p>The Kaplan-Meier estimate, <span class="math inline">\(\hat
S(t)\)</span>, is based on the product of all cases lower than or equal
to time <span class="math inline">\(t_i\)</span>, i.e.</p>
<p><span class="math display">\[\hat S(t) = \prod_{t_i &lt; t} (1 -
\frac{d_i}{n_i})\]</span></p>
</div>
<div id="the-cox-proportional-hazards" class="section level2">
<h2>The Cox proportional hazards</h2>
<p>The Cox proportional hazards model is the method by which we fit
models in order to estimate the <em>hazard rate</em> <span
class="math inline">\(\lambda(t)\)</span>, which in continuous time is a
conditional probability that during a very short interval <span
class="math inline">\(\Delta t\)</span> the failure event will take
place. THe hazard function is itself related to the survival function by
the ratio <span class="math inline">\(\lambda(t) =
\frac{f(t)}{S(t)}\)</span>, where <span
class="math inline">\(f(t)\)</span> is the the probability density
function.</p>
<p>The general form of the Cox model is as follows</p>
<p><span class="math display">\[\lambda(t|\vec x_i) = \lambda_0 (t)
\exp(\vec \beta_i^T \vec x_i)\]</span></p>
<p>where <span class="math inline">\(\vec x_i\)</span> is the vector of
covariates for the <span class="math inline">\(i\)</span>th subject,
<span class="math inline">\(\beta_i\)</span> is the vector of
coefficients, and <span class="math inline">\(\lambda_0(t)\)</span> is
the baseline hazard function.</p>
<p>All analyses were conducted in R, most notably the
<code>survival</code> package for its suite of functions for fitting
survival curves and the Cox model.</p>
<p>In order to determine which variables were appropriate for adding
into the model, we employed the log-rank test, which compares the
survival distribution of separate groups, in a manner similar to the
Cochran-Mantel-Haenszel test, which itself considers a binary predictor
to a binary outcome, groups them in strata and then compares the
respective distributions to test the null hypothesis that there is no
association between the predictor and the outcome. The log-rank test
operates similarly in a manner such that the different strata are
grouped by time <span class="math inline">\(t\)</span>.</p>
<p>Aside from fitting the model with baseline albumin, we were also
interested in treating albumin as a time varying covariate, as we have
data on albumin measurements for each subject throughout their time in
the study, spaced about 1-2 months apart. The motivation behind this is
to measure the effect of albumin on the risk of mortality across
time.</p>
<p>The motive behind treating albumin alternatingly as a static and time
varying covariate is to observe the different effect on the measured
association between mortality and albumin level that stems from the two
paradigms. Because a hemodialysis patient’s albumin level is constantly
in flux as the status of their health wavers, we believe that a model
that incorporates that additional information would be more useful,
rather than treating the albumin level at static to what its value is at
baseline.</p>
<p>When adding continuous covariates into the model, we looked at plots
of martingale residuals of Cox models vs standard OLS residuals were
create (see Appendix) in order to determine ideal transformations.
Neither the square-root transformation nor the log proved clearly ideal
when transforming cholesterol as a variable, but nevertheless we opted
to utilize the latter transformation.</p>
</div>
<div id="motivations-for-our-model" class="section level2">
<h2>Motivations for Our Model</h2>
<p>Our primary goal was to measure the association between mortality
(risk of death) and albumin, both at baseline and over time. We also
wanted to measure the effect having a history of cardiovascular disease
has on the association between mortality and albumin. As such, four
different models were ultimately fit: 1) the model which treats serum
albumin at baseline as constant (non-time varying), 2) the model which
treats serum albumin at baseline as constant <em>and</em> includes an
interaction term between serum albumin and the subject’s history of
cardiovascular disease, 3) the model which treats serum albumin as a
time-varying covariate, and finally 4) the model which treats serum
albumin as a time-varying covariate as well as including the interaction
term.</p>
<p>The inclusion of an interaction term in the Cox model introduces a
concept called <em>effect modification</em>, in which we hypothesize
that some variable’s association with the outcome (death) varies by
different strata of another variable, known as the effect modifier.
While confounding variables are superfluous and we correct for them to
avoid incurring bias in our study, effect modifiers provide additional
information and context on their covariates’ supposed association with
mortality.</p>
</div>
<div id="proportional-hazard-assumptions" class="section level2">
<h2>Proportional Hazard Assumptions</h2>
<p>In the following figure we are looking at the survival function
between the aforementioned levels of albumin, but are also introducing a
second covariate, this time with only two levels: history of
cardiovascular disease. Immediately we can see that the golden curve,
which corresponds to low baseline albumin and a history of
cardiovascular disease, is starkly different from any other survival
function. The top two curves, in green and blue, are those which
correspond to subjects without a history of cardiovascular disease and
had medium or high amounts of albumin at baseline, respectively.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a><span class="co"># K-M survival estimate</span></span>
<span id="cb2-2"><a href="#cb2-2" tabindex="-1"></a><span class="fu">survfit2</span>(<span class="fu">Surv</span>(tdeath, death) <span class="sc">~</span> albumin0_grp <span class="sc">+</span> hist.cvd, <span class="at">data =</span> usrds) <span class="sc">%&gt;%</span> </span>
<span id="cb2-3"><a href="#cb2-3" tabindex="-1"></a>  <span class="fu">ggsurvfit</span>() <span class="sc">+</span></span>
<span id="cb2-4"><a href="#cb2-4" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb2-5"><a href="#cb2-5" tabindex="-1"></a> <span class="at">x =</span> <span class="st">&quot;Days&quot;</span>, </span>
<span id="cb2-6"><a href="#cb2-6" tabindex="-1"></a> <span class="at">y =</span> <span class="st">&quot;Survival probability&quot;</span>,</span>
<span id="cb2-7"><a href="#cb2-7" tabindex="-1"></a> <span class="at">title =</span> <span class="st">&quot;K-M estimates of groups of albumin at baseline and history of CVD&quot;</span>,</span>
<span id="cb2-8"><a href="#cb2-8" tabindex="-1"></a> <span class="at">subtitle =</span> <span class="st">&quot;Groups were divided by 0-33%, 33-66%, and 66-100% percentiles.&quot;</span>)</span></code></pre></div>
<p><img src="esrd-survival_files/figure-html/km-baseline-albumin-cvd-1.png" width="672" /></p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a><span class="co"># cumulative hazard</span></span>
<span id="cb3-2"><a href="#cb3-2" tabindex="-1"></a><span class="fu">survfit2</span>(<span class="fu">Surv</span>(tdeath, death) <span class="sc">~</span> albumin0_grp <span class="sc">+</span> hist.cvd, <span class="at">data =</span> usrds) <span class="sc">%&gt;%</span> </span>
<span id="cb3-3"><a href="#cb3-3" tabindex="-1"></a>  <span class="fu">ggsurvfit</span>(<span class="at">type =</span> <span class="st">&quot;cumhaz&quot;</span>) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb3-5"><a href="#cb3-5" tabindex="-1"></a> <span class="at">x =</span> <span class="st">&quot;Days&quot;</span>, </span>
<span id="cb3-6"><a href="#cb3-6" tabindex="-1"></a> <span class="at">y =</span> <span class="st">&quot;Cumulative hazard&quot;</span>,</span>
<span id="cb3-7"><a href="#cb3-7" tabindex="-1"></a> <span class="at">title =</span> <span class="st">&quot;K-M estimates of groups of albumin at baseline and history of CVD&quot;</span>,</span>
<span id="cb3-8"><a href="#cb3-8" tabindex="-1"></a> <span class="at">subtitle =</span> <span class="st">&quot;Groups were divided by 0-33%, 33-66%, and 66-100% percentiles.&quot;</span>)</span></code></pre></div>
<p><img src="esrd-survival_files/figure-html/km-baseline-albumin-cvd-2.png" width="672" /></p>
<p>The cumulative hazard plot shows intersection between the blue, red,
and pink curves, which represent the medium albumin/history of CVD, the
low albumin/no history of CVD, and the high albumin/history of CVD
groups respectively. Intersection/touching of hazard curves does give
some evidence that the respective true hazard curves are not
proportional to one another. A log-rank test of these groups testing the
hypothesis that all of said curves are equal was rejected with a p-value
of approximately 0 and a confidence level of 0.05.</p>
<p>Based on prior knowledge, scrutinizing survival curves, and
conducting log-rank tests, we decided to include race, appearance of
undernourishment, cholesterol, age, and diabetes as additional variables
in the Cox model in addition to albumin. History of cardiovascular
disease was included as an effect modification in two different models,
while body mass index and smoking were both regarded as confounding
variables, particularly with respect to their causal relationship with
diabetes.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a>coxph_1a <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(tdeath, death) <span class="sc">~</span> </span>
<span id="cb4-2"><a href="#cb4-2" tabindex="-1"></a>                    albumin<span class="fl">.0</span> <span class="sc">+</span> racegrp <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" tabindex="-1"></a>                    undnour <span class="sc">+</span> <span class="fu">log</span>(cholest) <span class="sc">+</span> age <span class="sc">+</span> </span>
<span id="cb4-4"><a href="#cb4-4" tabindex="-1"></a>                    diabetes <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" tabindex="-1"></a>                    <span class="fu">strata</span>(bmi_grp) <span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" tabindex="-1"></a>                    <span class="fu">strata</span>(smokegrp), </span>
<span id="cb4-7"><a href="#cb4-7" tabindex="-1"></a>                  <span class="at">data =</span> usrds)</span>
<span id="cb4-8"><a href="#cb4-8" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" tabindex="-1"></a><span class="co"># model with interaction between baseline albumin and cvd</span></span>
<span id="cb4-10"><a href="#cb4-10" tabindex="-1"></a>coxph_1b <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(tdeath, death) <span class="sc">~</span> </span>
<span id="cb4-11"><a href="#cb4-11" tabindex="-1"></a>                    albumin<span class="fl">.0</span> <span class="sc">+</span> racegrp  <span class="sc">+</span></span>
<span id="cb4-12"><a href="#cb4-12" tabindex="-1"></a>                    undnour <span class="sc">+</span> <span class="fu">log</span>(cholest) <span class="sc">+</span> age <span class="sc">+</span> diabetes <span class="sc">+</span></span>
<span id="cb4-13"><a href="#cb4-13" tabindex="-1"></a>                    <span class="fu">strata</span>(bmi_grp) <span class="sc">+</span> <span class="fu">strata</span>(smokegrp) <span class="sc">+</span></span>
<span id="cb4-14"><a href="#cb4-14" tabindex="-1"></a>                    hist.cvd <span class="sc">+</span> albumin<span class="fl">.0</span><span class="sc">:</span>hist.cvd, </span>
<span id="cb4-15"><a href="#cb4-15" tabindex="-1"></a>                  <span class="at">data =</span> usrds)</span>
<span id="cb4-16"><a href="#cb4-16" tabindex="-1"></a></span>
<span id="cb4-17"><a href="#cb4-17" tabindex="-1"></a></span>
<span id="cb4-18"><a href="#cb4-18" tabindex="-1"></a><span class="co"># model with albumin as a time-varying covariate</span></span>
<span id="cb4-19"><a href="#cb4-19" tabindex="-1"></a>coxph_2a <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(start, stop, death) <span class="sc">~</span> </span>
<span id="cb4-20"><a href="#cb4-20" tabindex="-1"></a>                    albumin <span class="sc">+</span> racegrp <span class="sc">+</span> undnour <span class="sc">+</span> </span>
<span id="cb4-21"><a href="#cb4-21" tabindex="-1"></a>                    <span class="fu">log</span>(cholest) <span class="sc">+</span> age <span class="sc">+</span> diabetes <span class="sc">+</span></span>
<span id="cb4-22"><a href="#cb4-22" tabindex="-1"></a>                    <span class="fu">strata</span>(smokegrp) <span class="sc">+</span> <span class="fu">strata</span>(bmi_grp),</span>
<span id="cb4-23"><a href="#cb4-23" tabindex="-1"></a>                    <span class="at">data =</span> usrds_tvc)</span>
<span id="cb4-24"><a href="#cb4-24" tabindex="-1"></a></span>
<span id="cb4-25"><a href="#cb4-25" tabindex="-1"></a><span class="co"># model with albumin as a time varying covariate + interaction with CVD</span></span>
<span id="cb4-26"><a href="#cb4-26" tabindex="-1"></a><span class="co"># with interaction with hist.cvd</span></span>
<span id="cb4-27"><a href="#cb4-27" tabindex="-1"></a>coxph_2b <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(start, stop, death) <span class="sc">~</span> </span>
<span id="cb4-28"><a href="#cb4-28" tabindex="-1"></a>                    albumin <span class="sc">+</span> racegrp <span class="sc">+</span> undnour <span class="sc">+</span> </span>
<span id="cb4-29"><a href="#cb4-29" tabindex="-1"></a>                    <span class="fu">log</span>(cholest) <span class="sc">+</span> age <span class="sc">+</span> diabetes <span class="sc">+</span></span>
<span id="cb4-30"><a href="#cb4-30" tabindex="-1"></a>                    <span class="fu">strata</span>(smokegrp) <span class="sc">+</span> <span class="fu">strata</span>(bmi_grp) <span class="sc">+</span></span>
<span id="cb4-31"><a href="#cb4-31" tabindex="-1"></a>                    hist.cvd <span class="sc">+</span> hist.cvd<span class="sc">:</span>albumin,</span>
<span id="cb4-32"><a href="#cb4-32" tabindex="-1"></a>                  <span class="at">data =</span> usrds_tvc)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Testing whether the covariates in the model that includes albumin as a
time-varying covariate also vary with time.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Covariate
</th>
<th style="text-align:right;">
P-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Albumin (over time)
</td>
<td style="text-align:right;">
0.040
</td>
</tr>
<tr>
<td style="text-align:left;">
Race
</td>
<td style="text-align:right;">
0.710
</td>
</tr>
<tr>
<td style="text-align:left;">
Appeared Undernourished
</td>
<td style="text-align:right;">
0.918
</td>
</tr>
<tr>
<td style="text-align:left;">
Log(Cholesterol)
</td>
<td style="text-align:right;">
0.482
</td>
</tr>
<tr>
<td style="text-align:left;">
Age
</td>
<td style="text-align:right;">
0.816
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetes
</td>
<td style="text-align:right;">
0.711
</td>
</tr>
</tbody>
</table>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Testing whether the covariates in the model that includes albumin as a
time-varying covariate along with an interaction with a history of CVD,
also vary with time.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Covariate
</th>
<th style="text-align:right;">
P-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Albumin (over time)
</td>
<td style="text-align:right;">
0.065
</td>
</tr>
<tr>
<td style="text-align:left;">
Race
</td>
<td style="text-align:right;">
0.916
</td>
</tr>
<tr>
<td style="text-align:left;">
Appeared Undernourished
</td>
<td style="text-align:right;">
0.985
</td>
</tr>
<tr>
<td style="text-align:left;">
Log(Cholesterol)
</td>
<td style="text-align:right;">
0.575
</td>
</tr>
<tr>
<td style="text-align:left;">
Age
</td>
<td style="text-align:right;">
0.752
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetes
</td>
<td style="text-align:right;">
0.465
</td>
</tr>
<tr>
<td style="text-align:left;">
History of CVD
</td>
<td style="text-align:right;">
0.369
</td>
</tr>
<tr>
<td style="text-align:left;">
Albumin (over time) x History of CVD
</td>
<td style="text-align:right;">
0.205
</td>
</tr>
</tbody>
</table>
<p>Based on these tables above, we see that none of the covariates vary
with time, apart from human serum albumin we know to treat as
time-varying. This is due to the respective p-values of the chi-squared
test where we compare the model that has the aforementioned covariate
with an interaction with time, versus a nested model that does not have
said interaction. All of these p-values are above our 0.05 significance
level, so the Cox proportional hazards are not violated in this
case.</p>
</div>
</div>
<div id="results" class="section level1">
<h1>Results</h1>
<div id="interpretation-of-parameter-estimates" class="section level2">
<h2>Interpretation of Parameter Estimates</h2>
<div id="the-baseline-albumin-model" class="section level3">
<h3>The baseline Albumin model</h3>
<p>Our first model, which is principally concerned with the effect of
albumin at baseline on the risk of mortality, is</p>
<p><span class="math display">\[\begin{align*}
\lambda(t) = \ &amp; \lambda_0(t) \exp(\beta_1 \text{albumin}_{t=0} +
\beta_2 1_\text{race=Black} + \beta_3 1_\text{race=Other} + \\
&amp; \beta_4 1_\text{\text{Undernourished=1}} + \beta_5
\log(\text{cholesterol}) + \beta_6 (\text{age}) + \beta_7
1_\text{Diabetes=1}
\end{align*}\]</span></p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Parameter estimates, CIs and p-values for the model with baseline serum
albumin.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Coefficient
</th>
<th style="text-align:right;">
exp(Coefficient)
</th>
<th style="text-align:right;">
Lower 95% CI
</th>
<th style="text-align:right;">
Upper 95% CI
</th>
<th style="text-align:right;">
P-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Albumin (at t=0)
</td>
<td style="text-align:right;">
-0.418
</td>
<td style="text-align:right;">
0.659
</td>
<td style="text-align:right;">
0.530
</td>
<td style="text-align:right;">
0.818
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Race = Black
</td>
<td style="text-align:right;">
-0.279
</td>
<td style="text-align:right;">
0.757
</td>
<td style="text-align:right;">
0.600
</td>
<td style="text-align:right;">
0.954
</td>
<td style="text-align:right;">
0.018
</td>
</tr>
<tr>
<td style="text-align:left;">
Race = Other
</td>
<td style="text-align:right;">
-0.225
</td>
<td style="text-align:right;">
0.799
</td>
<td style="text-align:right;">
0.507
</td>
<td style="text-align:right;">
1.259
</td>
<td style="text-align:right;">
0.333
</td>
</tr>
<tr>
<td style="text-align:left;">
Appeared Undernourished
</td>
<td style="text-align:right;">
0.711
</td>
<td style="text-align:right;">
2.036
</td>
<td style="text-align:right;">
1.600
</td>
<td style="text-align:right;">
2.591
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Log(Cholesterol)
</td>
<td style="text-align:right;">
-0.431
</td>
<td style="text-align:right;">
0.650
</td>
<td style="text-align:right;">
0.454
</td>
<td style="text-align:right;">
0.930
</td>
<td style="text-align:right;">
0.018
</td>
</tr>
<tr>
<td style="text-align:left;">
Age
</td>
<td style="text-align:right;">
0.041
</td>
<td style="text-align:right;">
1.042
</td>
<td style="text-align:right;">
1.033
</td>
<td style="text-align:right;">
1.050
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetes
</td>
<td style="text-align:right;">
0.365
</td>
<td style="text-align:right;">
1.440
</td>
<td style="text-align:right;">
1.157
</td>
<td style="text-align:right;">
1.792
</td>
<td style="text-align:right;">
0.001
</td>
</tr>
</tbody>
</table>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_1}) \approx
0.659\)</span>, we estimate that the relative risk of death is
approximately 34.1% lower when comparing the group which has a serum
albumin value at baseline one-unit () higher than that of another group
that has similar attributes with respect to race, whether they appeared
undernourished to the study nurse, their cholesterol levels, their ages,
and whether they have diabetes.</p>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_2}) \approx
0.757\)</span>, we estimate that the relative risk of death is
approximately 24.3% lower when comparing the group of black individuals
to the group of white individuals that are similar in their albumin
levels, whether they appeared undernourished, their cholesterol levels,
their ages, and whether they have diabetes.</p>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_3}) \approx
0.799\)</span>, we estimate that the relative risk of death is
approximately 15.3% lower when comparing the group of individuals whose
race is neither black nor white, to the group of white individuals that
are similar in their albumin levels, whether they appeared
undernourished, their cholesterol levels, their ages, and whether they
have diabetes.</p>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_4}) \approx
2.036\)</span>, we estimate that the relative risk of death is
approximately 2.036 times higher when comparing the group of individuals
who appear undernourished to the study nurse to those who did not but
are similar in their albumin levels, their race, their cholesterol
levels, their ages, and whether they have diabetes.</p>
<p>Based on <span class="math inline">\(\hat{\beta_5} \approx
-0.431\)</span>, we estimate that comparing one group that has 10%
higher cholesterol to another group with similar albumin levels, race,
cholesterol levels, and ages is associated with a multiplicative
difference of <span class="math inline">\(1.10^{\hat \beta_5} \approx
0.96\)</span>, or a 4% lower relative risk of death.</p>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_6}) \approx
1.042\)</span>, we estimate that the relative risk of death is
approximately 4.2% higher when comparing two groups that are 1 year
apart in age, that are similar in terms of their albumin levels over
time, whether they appear undernourished, their race, and their
cholesterol levels.</p>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_7}) \approx
1.44\)</span>, we estimate that the relative risk of death is
approximately 44% higher when comparing the group of individuals with
diabetes to the group without diabetes, but with similar albumin levels,
their race, cholesterol levels, whether they appear undernourished, and
their age.</p>
</div>
<div id="the-baseline-albumin-model-with-cvd-interaction"
class="section level3">
<h3>The baseline Albumin model with CVD interaction</h3>
<p>The second model introduced an interaction term for the effect of the
subject’s history of cardiovascular disease on the association between
albumin level and risk of death.</p>
<p><span class="math display">\[\begin{align*}
\lambda(t) =\ &amp; \lambda_0(t) \exp(\beta_1 \text{albumin}_{t=0} +
\beta_2 1_\text{race=Black} + \beta_3 1_\text{race=Other} + \\
&amp; \beta_4 1_\text{Undernourished=1} + \beta_5
\log(\text{cholesterol}) + \beta_6 (\text{age)} + \\
&amp; \beta_7 1_\text{Diabetes=1} + \beta_8 1_\text{CVD=1} + \beta_9
(\text{albumin}_{t=0} \times 1_\text{CVD=1})
\end{align*}\]</span></p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Parameter estimates, CIs and p-values for the model with baseline serum
albumin and an interaction with history of CVD.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Coefficient
</th>
<th style="text-align:right;">
exp(Coefficient)
</th>
<th style="text-align:right;">
Lower 95% CI
</th>
<th style="text-align:right;">
Upper 95% CI
</th>
<th style="text-align:right;">
P-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Albumin (at t=0)
</td>
<td style="text-align:right;">
-0.712
</td>
<td style="text-align:right;">
0.491
</td>
<td style="text-align:right;">
0.329
</td>
<td style="text-align:right;">
0.732
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Race = Black
</td>
<td style="text-align:right;">
-0.193
</td>
<td style="text-align:right;">
0.825
</td>
<td style="text-align:right;">
0.648
</td>
<td style="text-align:right;">
1.050
</td>
<td style="text-align:right;">
0.118
</td>
</tr>
<tr>
<td style="text-align:left;">
Race = Other
</td>
<td style="text-align:right;">
-0.207
</td>
<td style="text-align:right;">
0.813
</td>
<td style="text-align:right;">
0.503
</td>
<td style="text-align:right;">
1.315
</td>
<td style="text-align:right;">
0.399
</td>
</tr>
<tr>
<td style="text-align:left;">
Appeared Undernourished
</td>
<td style="text-align:right;">
0.687
</td>
<td style="text-align:right;">
1.988
</td>
<td style="text-align:right;">
1.541
</td>
<td style="text-align:right;">
2.564
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Log(Cholesterol)
</td>
<td style="text-align:right;">
-0.479
</td>
<td style="text-align:right;">
0.620
</td>
<td style="text-align:right;">
0.423
</td>
<td style="text-align:right;">
0.907
</td>
<td style="text-align:right;">
0.014
</td>
</tr>
<tr>
<td style="text-align:left;">
Age
</td>
<td style="text-align:right;">
0.033
</td>
<td style="text-align:right;">
1.034
</td>
<td style="text-align:right;">
1.024
</td>
<td style="text-align:right;">
1.043
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetes
</td>
<td style="text-align:right;">
0.245
</td>
<td style="text-align:right;">
1.278
</td>
<td style="text-align:right;">
1.010
</td>
<td style="text-align:right;">
1.617
</td>
<td style="text-align:right;">
0.041
</td>
</tr>
<tr>
<td style="text-align:left;">
History of CVD
</td>
<td style="text-align:right;">
-0.781
</td>
<td style="text-align:right;">
0.458
</td>
<td style="text-align:right;">
0.086
</td>
<td style="text-align:right;">
2.454
</td>
<td style="text-align:right;">
0.362
</td>
</tr>
<tr>
<td style="text-align:left;">
Albumin (at t=0) x History of CVD
</td>
<td style="text-align:right;">
0.432
</td>
<td style="text-align:right;">
1.540
</td>
<td style="text-align:right;">
0.964
</td>
<td style="text-align:right;">
2.460
</td>
<td style="text-align:right;">
0.071
</td>
</tr>
</tbody>
</table>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_1}) \approx
0.491\)</span>, we estimate that the relative risk of death is
approximately 50.9% lower when comparing the group which had a serum
albumin value at baseline one-unit higher than that of another group
that has similar attributes with respect to race, whether they appeared
undernourished to the study nurse, their cholesterol levels, their ages,
whether they have diabetes, and neither group has a history of
cardiovascular disease.</p>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_2}) \approx
0.825\)</span>, we estimate that the relative risk of death is
approximately 17.5% lower when comparing the group of black individuals
to the group of white individuals that are similar in their albumin
levels, whether they appeared undernourished, their cholesterol levels,
their ages, whether they have a history of cardiovascular disease, and
whether they have diabetes.</p>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_3}) \approx
0.813\)</span>, we estimate that the relative risk of death is
approximately 18.7% lower when comparing the group of individuals whose
race is neither black nor white, to the group of white individuals that
are similar in their albumin levels, whether they appeared
undernourished, their cholesterol levels, their ages, whether they have
a history of cardiovascular disease, and whether they have diabetes.</p>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_4}) \approx
1.988\)</span>, we estimate that the relative risk of death is
approximately 1.988 times higher when comparing the group of individuals
who appear undernourished to the study nurse to those who did not but
are similar in their albumin levels, their race, their cholesterol
levels, their ages, whether they have a history of cardiovascular
disease, and whether they have diabetes.</p>
<p>Based on <span class="math inline">\(\hat{\beta_5} \approx
-0.479\)</span>, we estimate that comparing one group that has 10%
higher cholesterol than another group with similar albumin levels, race,
cholesterol levels, ages, whether they have diabetes, and history of
cardiovascular disease is associated with a multiplicative difference of
<span class="math inline">\(1.10^{\hat \beta_5} \approx 0.955\)</span>
in the relative risk, or a 4.5% lower relative risk of death.</p>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_6}) \approx
1.034\)</span>, we estimate that the relative risk of death is
approximately 3.4% higher when comparing two groups that are 1 year
apart in age, that are similar in terms of their albumin levels over
time, whether they appear undernourished, their race, their cholesterol
levels, and whether they have diabetes.</p>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_7}) \approx
1.278\)</span>, we estimate that the relative risk of death is
approximately 27.8% higher when comparing a group with diabetes to a
group without, that are both similar in terms of their albumin levels
over time, whether they appear undernourished, their race, their
cholesterol levels, and their ages.</p>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_8}) \approx
0.458\)</span>, we estimate that the relative risk of death is
approximately 54.2% lower when comparing the group that has a history of
cardiovascular disease to the group that does not have a history of
cardiovascular disease and is similar in terms of albumin levels,
whether they appear undernourished, their race, their ages, their
cholesterol levels, and whether they have diabetes.</p>
<p>Our estimate for the exponential of the interaction term is <span
class="math inline">\(\exp(\hat{\beta_9}) \approx 1.540\)</span> If we
were to compare two groups, both with a history of cardiovascular
disease, and similar in terms of whether or not they appeared
undernourished, in their race, their cholesterol levels, and their
diabetes status, where one group would have their albumin at baseline as
some fixed value, and the other group with their baseline albumin at
some value 1 unit higher, the multiplicative difference in their
relative risk of death would be approximately <span
class="math inline">\(\exp(\hat \beta_1 + \hat \beta_9) \approx
0.756\)</span>, i.e. their relative risk of death of the first group
would be approximately 24.4% lower. It is also assumed we are adjusting
for body mass index and smoking history as confounders.</p>
</div>
<div id="the-time-varying-albumin-model" class="section level3">
<h3>The time-varying Albumin model</h3>
<p>The third model treats albumin as a time-varying covariate.</p>
<p><span class="math display">\[\begin{align*}
\lambda(t) = \ &amp;\lambda_0(t) \exp(\beta_1 \text{albumin}_{t} +
\beta_2 1_\text{race=Black} + \beta_3 1_\text{race=Other} + \\
&amp; \beta_4 1_\text{Undernourished=1} + \beta_5
\log(\text{cholesterol}) + \beta_6 (\text{age} + \beta_7
1_\text{Diabetes=1}
\end{align*}\]</span></p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Parameter estimates, CIs and p-values for the model with time-varying
serum albumin.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Coefficient
</th>
<th style="text-align:right;">
exp(Coefficient)
</th>
<th style="text-align:right;">
Lower 95% CI
</th>
<th style="text-align:right;">
Upper 95% CI
</th>
<th style="text-align:right;">
P-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Albumin (over time)
</td>
<td style="text-align:right;">
-0.599
</td>
<td style="text-align:right;">
0.549
</td>
<td style="text-align:right;">
0.485
</td>
<td style="text-align:right;">
0.622
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Race = Black
</td>
<td style="text-align:right;">
-0.271
</td>
<td style="text-align:right;">
0.763
</td>
<td style="text-align:right;">
0.675
</td>
<td style="text-align:right;">
0.862
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Race = Other
</td>
<td style="text-align:right;">
-0.154
</td>
<td style="text-align:right;">
0.857
</td>
<td style="text-align:right;">
0.681
</td>
<td style="text-align:right;">
1.079
</td>
<td style="text-align:right;">
0.188
</td>
</tr>
<tr>
<td style="text-align:left;">
Appeared Undernourished
</td>
<td style="text-align:right;">
0.549
</td>
<td style="text-align:right;">
1.732
</td>
<td style="text-align:right;">
1.529
</td>
<td style="text-align:right;">
1.962
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Log(Cholesterol)
</td>
<td style="text-align:right;">
-0.172
</td>
<td style="text-align:right;">
0.842
</td>
<td style="text-align:right;">
0.693
</td>
<td style="text-align:right;">
1.023
</td>
<td style="text-align:right;">
0.083
</td>
</tr>
<tr>
<td style="text-align:left;">
Age
</td>
<td style="text-align:right;">
0.037
</td>
<td style="text-align:right;">
1.038
</td>
<td style="text-align:right;">
1.034
</td>
<td style="text-align:right;">
1.043
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetes
</td>
<td style="text-align:right;">
0.320
</td>
<td style="text-align:right;">
1.377
</td>
<td style="text-align:right;">
1.227
</td>
<td style="text-align:right;">
1.545
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
</tbody>
</table>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_1}) \approx
0.549\)</span>, we estimate that the relative risk of death is
approximately 45.1% lower when comparing the group which has a serum
albumin value one-unit higher than that of another group at the same
period at which their albumin level was recorded; the groups also have
similar attributes with respect to race, whether they appeared
undernourished to the study nurse, their cholesterol levels, and their
ages,</p>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_2}) \approx
0.763\)</span>, we estimate that the relative risk of death is
approximately 23.7% lower when comparing the group of black individuals
to the group of white individuals that are similar in their albumin
levels over time, whether they appeared undernourished, their
cholesterol levels, their ages, and whether they have diabetes.</p>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_3}) \approx
0.857\)</span>, we estimate that the relative risk of death is
approximately 14.3% lower when comparing the group of individuals whose
race is neither black nor white, to the group of white individuals that
are similar in their albumin levels over time, whether they appeared
undernourished, their cholesterol levels, their ages, and whether they
have diabetes.</p>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_4}) \approx
1.732\)</span>, we estimate that the relative risk of death is
approximately 73.2% higher when comparing the group of individuals who
appear undernourished to the study nurse to those who did not but are
similar in their albumin levels over time, their race, their cholesterol
levels, their ages, and whether they have diabetes.</p>
<p>Based on <span class="math inline">\(\hat{\beta_5} \approx
-0.172\)</span>, we estimate that comparing one group that has 10%
higher cholesterol than another group with similar albumin levels over
time, race, cholesterol levels, ages, and whether they have diabetes, is
associated with a multiplicative difference of <span
class="math inline">\(1.10^{\hat \beta_5} \approx 0.984\)</span>, or a
1.6% lower relative risk of death.</p>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_6}) \approx
1.038\)</span>, we estimate that the relative risk of death is
approximately 3.8% higher when comparing two groups that are 1 year
apart in age, that are similar in terms of their albumin levels over
time, whether they appear undernourished, their race, and their
cholesterol levels.</p>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_7}) \approx
1.377\)</span>, we estimate that the relative risk of death is
approximately 37.7% higher when comparing a group with diabetes to
another group without, that are both similar in terms of their albumin
levels over time, whether they appear undernourished, their race, their
cholesterol levels, and their ages.</p>
</div>
<div id="the-time-varying-albumin-model-with-cvd-interaction"
class="section level3">
<h3>The time-varying Albumin model with CVD interaction</h3>
<p>The fourth and final model treats albumin as a time-varying covariate
and also includes an interaction term representing the effect of the
subject’s history of cardiovascular disease on the association between
albumin level and risk of mortality.</p>
<p><span class="math display">\[\begin{align*}
\lambda(t) =\ &amp; \lambda_0(t) \exp(\beta_1 \text{albumin}_t + \beta_2
1_\text{race=Black} + \beta_3 1_\text{race=Other} + \\
&amp; \beta_4 1_\text{Undernourished=1} + \beta_5
\log(\text{cholesterol}) + \beta_6 (\text{age} +  \\
&amp; \beta_7 1_\text{Diabetes=1} + \beta_8 1_\text{CVD=1} + \beta_9
(\text{albumin}_{t=0} \times 1_\text{CVD=1})
\end{align*}\]</span></p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Parameter estimates, CIs and p-values for the model with time-varying
serum albumin and an interaction with history of CVD.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Coefficient
</th>
<th style="text-align:right;">
exp(Coefficient)
</th>
<th style="text-align:right;">
Lower 95% CI
</th>
<th style="text-align:right;">
Upper 95% CI
</th>
<th style="text-align:right;">
P-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Albumin (over time)
</td>
<td style="text-align:right;">
-0.998
</td>
<td style="text-align:right;">
0.369
</td>
<td style="text-align:right;">
0.290
</td>
<td style="text-align:right;">
0.469
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Race = Black
</td>
<td style="text-align:right;">
-0.210
</td>
<td style="text-align:right;">
0.811
</td>
<td style="text-align:right;">
0.715
</td>
<td style="text-align:right;">
0.920
</td>
<td style="text-align:right;">
0.001
</td>
</tr>
<tr>
<td style="text-align:left;">
Race = Other
</td>
<td style="text-align:right;">
-0.196
</td>
<td style="text-align:right;">
0.822
</td>
<td style="text-align:right;">
0.643
</td>
<td style="text-align:right;">
1.051
</td>
<td style="text-align:right;">
0.118
</td>
</tr>
<tr>
<td style="text-align:left;">
Appeared Undernourished
</td>
<td style="text-align:right;">
0.520
</td>
<td style="text-align:right;">
1.682
</td>
<td style="text-align:right;">
1.478
</td>
<td style="text-align:right;">
1.915
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Log(Cholesterol)
</td>
<td style="text-align:right;">
-0.231
</td>
<td style="text-align:right;">
0.793
</td>
<td style="text-align:right;">
0.648
</td>
<td style="text-align:right;">
0.971
</td>
<td style="text-align:right;">
0.025
</td>
</tr>
<tr>
<td style="text-align:left;">
Age
</td>
<td style="text-align:right;">
0.030
</td>
<td style="text-align:right;">
1.030
</td>
<td style="text-align:right;">
1.026
</td>
<td style="text-align:right;">
1.035
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetes
</td>
<td style="text-align:right;">
0.183
</td>
<td style="text-align:right;">
1.201
</td>
<td style="text-align:right;">
1.063
</td>
<td style="text-align:right;">
1.358
</td>
<td style="text-align:right;">
0.003
</td>
</tr>
<tr>
<td style="text-align:left;">
History of CVD
</td>
<td style="text-align:right;">
-1.250
</td>
<td style="text-align:right;">
0.286
</td>
<td style="text-align:right;">
0.105
</td>
<td style="text-align:right;">
0.779
</td>
<td style="text-align:right;">
0.014
</td>
</tr>
<tr>
<td style="text-align:left;">
Albumin (over time) x History of CVD
</td>
<td style="text-align:right;">
0.553
</td>
<td style="text-align:right;">
1.738
</td>
<td style="text-align:right;">
1.316
</td>
<td style="text-align:right;">
2.295
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
</tbody>
</table>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_1}) \approx
0.369\)</span>, we estimate that the relative risk of death is
approximately 63.1% lower when comparing the group which had a serum
albumin value at baseline one-unit higher than that of another group
that has similar attributes with respect to race, whether they appeared
undernourished to the study nurse, their cholesterol levels, their ages,
and neither group has cardiovascular disease.</p>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_2}) \approx
0.811\)</span>, we estimate that the relative risk of death is
approximately 18.9% lower when comparing the group of black individuals
to the group of white individuals that are similar in their albumin
levels, whether they appeared undernourished, their cholesterol levels,
their ages, whether they have a history of cardiovascular disease, and
whether they have diabetes, while adjusting for body mass index and
smoking history.</p>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_3}) \approx
0.822\)</span>, we estimate that the relative risk of death is
approximately 17.8% lower when comparing the group of individuals whose
race is neither black nor white, to the group of white individuals that
are similar in their albumin levels, whether they appeared
undernourished, their cholesterol levels, their ages, whether they have
a history of cardiovascular disease, and whether they have diabetes,
while adjusting for body mass index and smoking history.</p>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_4}) \approx
1.682\)</span>, we estimate that the relative risk of death is
approximately 68.2% higher when comparing the group of individuals who
appear undernourished to the study nurse to those who did not but are
similar in their albumin levels, their race, their cholesterol levels,
their ages, whether they have a history of cardiovascular disease, and
whether they have diabetes, while adjusting for body mass index and
smoking history.</p>
<p>Based on <span class="math inline">\(\hat{\beta_5} \approx
-0.231\)</span>, we estimate that comparing one group that has 10%
higher cholesterol than another group with similar albumin levels, race,
cholesterol levels, ages, history of cardiovascular disease, and
diabetes status (while adjusting for body mass index and smoking
history) is associated with a multiplicative difference of <span
class="math inline">\(1.10^{\hat \beta_5} \approx 0.978\)</span> in the
relative risk, or a 2.2% lower relative risk of death.</p>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_6}) \approx
1.03\)</span>, we estimate that the relative risk of death is
approximately 3% higher when comparing two groups that are 1 year apart
in age, that are similar in terms of their albumin levels over time,
whether they appear undernourished, their race, their cholesterol
levels, and diabetes status, while adjusting for body mass index and
smoking history.</p>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_7}) \approx
1.201\)</span>, we estimate that the relative risk of death is
approximately 20.1% higher when comparing a group with diabetes to
another group without, that are both similar in terms of their albumin
levels over time, whether they appear undernourished, their race, their
cholesterol levels, and their ages, while adjusting for body mass index
and smoking history.</p>
<p>Based on <span class="math inline">\(\exp(\hat{\beta_8}) \approx
0.286\)</span>, we estimate that the relative risk of death is
approximately 71.4% lower when comparing the group that has a history of
cardiovascular disease to the group that does not have a history of
cardiovascular disease and is similar in terms of albumin levels,
whether they appear undernourished, their race, their ages, their
cholesterol levels, and their diabetes status, while adjusting for body
mass index and smoking history.</p>
<p>Our estimate for the exponential of the interaction term is <span
class="math inline">\(\exp(\hat{\beta_9}) \approx 1.738\)</span>. If we
were to compare two groups, both with a history of cardiovascular
disease, and similar in terms of whether or not they appeared
undernourished, in their race, and their cholesterol levels, where would
have their albumin at baseline as some fixed value, and the other group
with their baseline albumin at some value 1 unit higher, the
multiplicative difference in their relative risk of death would be
approximately <span class="math inline">\(\exp(\hat \beta_1 + \hat
\beta_9) \approx 0.628\)</span>, i.e. their relative risk of death of
the first group would be approximately 37% lower. It is also assumed we
are adjusting for body mass index and smoking history as
confounders.</p>
</div>
</div>
</div>
<div id="discussion" class="section level1">
<h1>Discussion</h1>
<p>Among all of the models fit, we believe the best among them to be
that which treats albumin as a time-varying covariate as well as
includes the effect modification term that reflects how having a history
of cardiovascular disease affects the association between albumin and
the relative risk of death. Overall, the results from all four models
are reflective of our preliminary hypothesis which is that serum albumin
is associated with mortality among ESRD patients, on account of it being
a reflection of how healthy a person is. Notably, the interaction
between serum albumin and history of CVD is significant at a 0.05 level
when albumin is treated as time-varying.</p>
<p>Many of the model coefficients for each covariate seemed relatively
unchanged when going from model to model, with some exceptions. Notably,
the effect of being of race “other” (neither black nor white) was seen
as being associated with a lower relative risk of death in all but one
of the models, the exception being the final model which included
albumin as a time-varying covariate as well as the interaction with the
history of CVD. The direction of the association of appearing
undernourished was also inverted when going from having a positive
association with the relative risk in the first three models to having a
negative association.</p>
<p>Insofar as limitations of the study, there are certainly some
shortcomings to consider, namely the lack of other confounding variables
(such as drug use or alcohol use) being included in the data. Limiting
the racial group category to a three-level factor variable also
minimizes the extent to which we can quantify the effect race has on
mortality with respect to albumin or other covariates in our model.
Being that many minority groups are underrepresented in medical research
despite their disproportionate amount of medical issues, this would be
something to consider addressing going forward in future studies.</p>
<p>One of the difficulties in the analysis was identifying an
appropriate functional form for certain continuous covariates such as
cholesterol. The efforts of trying to ascertain said functional form can
be found in the Appendix. Many different transformations including the
log transformation and the square root transformation were attempted but
few seemed to cause an appreciable difference when looking at the
martingale residuals of the Cox model free of cholesterol versus the
standard residuals of the respective OLS model regressing all of the
other covariates against cholesterol.</p>
<p>Future work should be dedicated to exploring more deeply the
case-control study design and seeing what those outcomes would be
relative to those compared here.</p>
<div style="page-break-after: always;"></div>
</div>
<div id="appendix" class="section level1">
<h1>Appendix</h1>
<pre><code>## 
## Sampling risk sets: .................................................................................................................................................................................................................................................................................</code></pre>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Parameter estimates, CIs and p-values for the nested case-control model.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Coefficient
</th>
<th style="text-align:right;">
exp(Coefficient)
</th>
<th style="text-align:right;">
Lower 95% CI
</th>
<th style="text-align:right;">
Upper 95% CI
</th>
<th style="text-align:right;">
P-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Albumin (at t=0)
</td>
<td style="text-align:right;">
-0.628
</td>
<td style="text-align:right;">
0.534
</td>
<td style="text-align:right;">
0.344
</td>
<td style="text-align:right;">
0.828
</td>
<td style="text-align:right;">
0.005
</td>
</tr>
<tr>
<td style="text-align:left;">
Race = Black
</td>
<td style="text-align:right;">
-0.433
</td>
<td style="text-align:right;">
0.649
</td>
<td style="text-align:right;">
0.415
</td>
<td style="text-align:right;">
1.013
</td>
<td style="text-align:right;">
0.057
</td>
</tr>
<tr>
<td style="text-align:left;">
Race = Other
</td>
<td style="text-align:right;">
-0.636
</td>
<td style="text-align:right;">
0.529
</td>
<td style="text-align:right;">
0.232
</td>
<td style="text-align:right;">
1.209
</td>
<td style="text-align:right;">
0.131
</td>
</tr>
<tr>
<td style="text-align:left;">
Appeared Undernourished
</td>
<td style="text-align:right;">
0.578
</td>
<td style="text-align:right;">
1.782
</td>
<td style="text-align:right;">
1.108
</td>
<td style="text-align:right;">
2.867
</td>
<td style="text-align:right;">
0.017
</td>
</tr>
<tr>
<td style="text-align:left;">
Log(Cholesterol)
</td>
<td style="text-align:right;">
-0.414
</td>
<td style="text-align:right;">
0.661
</td>
<td style="text-align:right;">
0.327
</td>
<td style="text-align:right;">
1.336
</td>
<td style="text-align:right;">
0.249
</td>
</tr>
<tr>
<td style="text-align:left;">
Age
</td>
<td style="text-align:right;">
0.035
</td>
<td style="text-align:right;">
1.036
</td>
<td style="text-align:right;">
1.020
</td>
<td style="text-align:right;">
1.051
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetes
</td>
<td style="text-align:right;">
0.490
</td>
<td style="text-align:right;">
1.632
</td>
<td style="text-align:right;">
1.104
</td>
<td style="text-align:right;">
2.414
</td>
<td style="text-align:right;">
0.014
</td>
</tr>
</tbody>
</table>
<pre><code>## 
## Sampling risk sets: .................................................................................................................................................................................................................................................................................</code></pre>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Parameter estimates, CIs and p-values for the nested case-control model
with an interaction.
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Coefficient
</th>
<th style="text-align:right;">
exp(Coefficient)
</th>
<th style="text-align:right;">
Lower 95% CI
</th>
<th style="text-align:right;">
Upper 95% CI
</th>
<th style="text-align:right;">
P-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Albumin (at t=0)
</td>
<td style="text-align:right;">
-0.891
</td>
<td style="text-align:right;">
0.410
</td>
<td style="text-align:right;">
0.188
</td>
<td style="text-align:right;">
0.897
</td>
<td style="text-align:right;">
0.026
</td>
</tr>
<tr>
<td style="text-align:left;">
Race = Black
</td>
<td style="text-align:right;">
-0.247
</td>
<td style="text-align:right;">
0.781
</td>
<td style="text-align:right;">
0.480
</td>
<td style="text-align:right;">
1.272
</td>
<td style="text-align:right;">
0.321
</td>
</tr>
<tr>
<td style="text-align:left;">
Race = Other
</td>
<td style="text-align:right;">
-0.262
</td>
<td style="text-align:right;">
0.769
</td>
<td style="text-align:right;">
0.332
</td>
<td style="text-align:right;">
1.782
</td>
<td style="text-align:right;">
0.541
</td>
</tr>
<tr>
<td style="text-align:left;">
Appeared Undernourished
</td>
<td style="text-align:right;">
0.138
</td>
<td style="text-align:right;">
1.148
</td>
<td style="text-align:right;">
0.642
</td>
<td style="text-align:right;">
2.052
</td>
<td style="text-align:right;">
0.641
</td>
</tr>
<tr>
<td style="text-align:left;">
Log(Cholesterol)
</td>
<td style="text-align:right;">
-0.500
</td>
<td style="text-align:right;">
0.606
</td>
<td style="text-align:right;">
0.272
</td>
<td style="text-align:right;">
1.354
</td>
<td style="text-align:right;">
0.222
</td>
</tr>
<tr>
<td style="text-align:left;">
Age
</td>
<td style="text-align:right;">
0.035
</td>
<td style="text-align:right;">
1.036
</td>
<td style="text-align:right;">
1.018
</td>
<td style="text-align:right;">
1.055
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetes
</td>
<td style="text-align:right;">
0.242
</td>
<td style="text-align:right;">
1.273
</td>
<td style="text-align:right;">
0.778
</td>
<td style="text-align:right;">
2.084
</td>
<td style="text-align:right;">
0.336
</td>
</tr>
<tr>
<td style="text-align:left;">
History of CVD
</td>
<td style="text-align:right;">
-1.277
</td>
<td style="text-align:right;">
0.279
</td>
<td style="text-align:right;">
0.008
</td>
<td style="text-align:right;">
9.920
</td>
<td style="text-align:right;">
0.483
</td>
</tr>
<tr>
<td style="text-align:left;">
Albumin (over time) x History of CVD
</td>
<td style="text-align:right;">
0.643
</td>
<td style="text-align:right;">
1.903
</td>
<td style="text-align:right;">
0.717
</td>
<td style="text-align:right;">
5.052
</td>
<td style="text-align:right;">
0.196
</td>
</tr>
</tbody>
</table>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Likelihood ratio test for comparing the model with the interaction to
the one without.
</caption>
<thead>
<tr>
<th style="text-align:right;">
LRT Test Statistic
</th>
<th style="text-align:right;">
Degrees of Freedom
</th>
<th style="text-align:right;">
P-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
126.5685
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
The results of the log-rank test before and after stratifying by
confounders BMI and smoking history. Without adjusting for the
confounding variables, diabetes is not considered significantly
associated with risk of death.
</caption>
<thead>
<tr>
<th style="text-align:left;">
Log-rank Test vs Death
</th>
<th style="text-align:right;">
P-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Diabetes Only
</td>
<td style="text-align:right;">
0.0539612
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetes, stratified by BMI
</td>
<td style="text-align:right;">
0.0024214
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetes, stratified by Smoking History
</td>
<td style="text-align:right;">
0.0272681
</td>
</tr>
</tbody>
</table>
<pre><code>## The `tbl_survfit()` function supports `survfit()` objects with a single
## stratifying variable, and it looks like you may have more. Errors or unexpected
## output may occur.</code></pre>
<div id="byrbootpdz" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#byrbootpdz table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#byrbootpdz thead, #byrbootpdz tbody, #byrbootpdz tfoot, #byrbootpdz tr, #byrbootpdz td, #byrbootpdz th {
  border-style: none;
}

#byrbootpdz p {
  margin: 0;
  padding: 0;
}

#byrbootpdz .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#byrbootpdz .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#byrbootpdz .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#byrbootpdz .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#byrbootpdz .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#byrbootpdz .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#byrbootpdz .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#byrbootpdz .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#byrbootpdz .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#byrbootpdz .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#byrbootpdz .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#byrbootpdz .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#byrbootpdz .gt_spanner_row {
  border-bottom-style: hidden;
}

#byrbootpdz .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#byrbootpdz .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#byrbootpdz .gt_from_md > :first-child {
  margin-top: 0;
}

#byrbootpdz .gt_from_md > :last-child {
  margin-bottom: 0;
}

#byrbootpdz .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#byrbootpdz .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#byrbootpdz .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#byrbootpdz .gt_row_group_first td {
  border-top-width: 2px;
}

#byrbootpdz .gt_row_group_first th {
  border-top-width: 2px;
}

#byrbootpdz .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#byrbootpdz .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#byrbootpdz .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#byrbootpdz .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#byrbootpdz .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#byrbootpdz .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#byrbootpdz .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#byrbootpdz .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#byrbootpdz .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#byrbootpdz .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#byrbootpdz .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#byrbootpdz .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#byrbootpdz .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#byrbootpdz .gt_left {
  text-align: left;
}

#byrbootpdz .gt_center {
  text-align: center;
}

#byrbootpdz .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#byrbootpdz .gt_font_normal {
  font-weight: normal;
}

#byrbootpdz .gt_font_bold {
  font-weight: bold;
}

#byrbootpdz .gt_font_italic {
  font-style: italic;
}

#byrbootpdz .gt_super {
  font-size: 65%;
}

#byrbootpdz .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#byrbootpdz .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#byrbootpdz .gt_indent_1 {
  text-indent: 5px;
}

#byrbootpdz .gt_indent_2 {
  text-indent: 10px;
}

#byrbootpdz .gt_indent_3 {
  text-indent: 15px;
}

#byrbootpdz .gt_indent_4 {
  text-indent: 20px;
}

#byrbootpdz .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;Characteristic&lt;/strong&gt;"><strong>Characteristic</strong></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1" scope="col" id="&lt;strong&gt;1-year survival (95% CI)&lt;/strong&gt;"><strong>1-year survival (95% CI)</strong></th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="label" class="gt_row gt_left">albumin0_grp</td>
<td headers="stat_1" class="gt_row gt_center"><br /></td></tr>
    <tr><td headers="label" class="gt_row gt_left">    [0.6,3.6], hist.cvd=N</td>
<td headers="stat_1" class="gt_row gt_center">80% (75%, 85%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    [0.6,3.6], hist.cvd=Y</td>
<td headers="stat_1" class="gt_row gt_center">63% (59%, 68%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    (3.6,3.9], hist.cvd=N</td>
<td headers="stat_1" class="gt_row gt_center">92% (88%, 95%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    (3.6,3.9], hist.cvd=Y</td>
<td headers="stat_1" class="gt_row gt_center">77% (73%, 82%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    (3.9,7], hist.cvd=N</td>
<td headers="stat_1" class="gt_row gt_center">97% (96%, 99%)</td></tr>
    <tr><td headers="label" class="gt_row gt_left">    (3.9,7], hist.cvd=Y</td>
<td headers="stat_1" class="gt_row gt_center">81% (76%, 85%)</td></tr>
  </tbody>
  
  
</table>
</div>
<p><img src="esrd-survival_files/figure-html/survfit-baseline-albumin-binary-1.png" width="672" /><img src="esrd-survival_files/figure-html/survfit-baseline-albumin-binary-2.png" width="672" /></p>
<div style="page-break-after: always;"></div>
</div>
<div id="references" class="section level1">
<h1>References</h1>
<p>Chung-Eun Ha, Nadhipuram V. Bhagavan, Novel insights into the
pleiotropic effects of human serum albumin in health and disease,
Biochimica et Biophysica Acta (BBA) - General Subjects, Volume 1830,
Issue 12, 2013, Pages 5486-5493, ISSN 0304-4165, <a
href="https://doi.org/10.1016/j.bbagen.2013.04.012"
class="uri">https://doi.org/10.1016/j.bbagen.2013.04.012</a>.</p>
<p>Gardner JD, Mouton AJ. Alcohol effects on cardiac function. Compr
Physiol. 2015 Apr;5(2):791-802. doi: 10.1002/cphy.c140046. PMID:
25880513.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
