---
title: "Resume"
output:
  html_document:
    includes:
      in_header: 
        header.html
navbar:
  title: "Home"
  left:
    - text: "About Me"
      href: about_me.html
    - text: "Resume"
      href: resume.html
    - text: "Projects"
      menu:
        - text: "Survival analysis of kidney disease patients"
          href: esrd-survival.html
        - text: "Spatial modeling of school gun violence"
          href: matern-spatial.html
        - text: "Sexual network exponential random graph modeling"
          href: ergm_models.html
        - text: "Classifying wine quality"
          href: wine-classification.html
        - text: "Forecasting bitcoin value"
          href: bitcoin.html
        - text: "Predicting housing prices"
          href: housing-prices.html
        - text: "Play Gomoku using Shiny"
          href: ggomoku.html
    - text: "Contact Me"
      menu:
        - text: "jsteven.raquel8@gmail.com"
          href: mailto:jsteven.raquel8@gmail.com
        - text: "GitHub"
          href: https://github.com/jstevenr
        - text: "LinkedIn"
          href: https://www.linkedin.com/in/jstevenr/
---

Statistician with a strong academic background and expertise in statistical analysis and modeling, seeking a challenging position as a statistician or analyst. With a Master’s degree in Statistics and coursework covering advanced statistical methodologies, I am equipped with the skills to design and implement statistical studies, analyze complex data sets, and provide evidence-based insights in the field of healthcare or research. Proficient in various programming languages such as R and Python, I am eager to apply my statistical expertise to contribute to meaningful research projects, clinical trials, and public health initiatives.

## Education

* **Statistics M.S.**, University of California, Irvine, March 2023
    + Coursework in Probability and Statistical Theory, Statistical Methods in Linear Models, Categorical Data and Longitudinal Data, Bayesian Data Analysis, Infectious Disease Modeling, Spatial Statistics, Social Network Data, Survival Analysis
    + Designed the `ggomoku` R package and Shiny app as a pair project
* **Statistical Science B.S.**, University of California, Santa Barbara, June 2018
    + Concentration in Applied Statistics
    + Coursework in Data Mining, Regression Analysis, Stochastic Processes, Non-Parametric Methods, Time Series, Advanced Statistical Methods, SAS Programming, Statistical Data Science
    
## Skills

* **Software Tools and Languages**
    + R, Python, SQL, SAS, Stata
    + Windows, Linux
    + Bash Shell, Git, Markdown, LaTeX
    + Microsoft Excel, Microsoft Power BI, Tableau, SAP Analytics Cloud
* **Languages**
    + Spanish (B1), Portuguese (B1)

## Research Experience

* **University of California, Irvine**, Mar 2022 - Jun 2022
    + Collaborated with Dr. Veronica Berrocal to analyze and visualize the spatial distribution of immune system cells relative to cancer outcome. Employed advanced statistical techniques and designed custom R functions to handle large-scale spatial data.

## Work Experience

* **Water Equity Lab Project Policy Analyst** [Water Equity Lab, UC Irvine](https://www.uci.edu/), Jul 2022 - Apr 2023
    + Analyzed and processed vector and raster data to identify disparities in access to water infrastructure among minority
demographics.
    + Developed over 50 R functions utilizing the sf package, resulting in streamlined productivity for the team.

* **Data Analyst**, [Valeo Networks](https://valeonetworks.com), Sep 2018 - Sep 2020
    + Implemented predictive analytics solutions to identify trends and patterns in large datasets, contributing to data-driven decision-making.
    + Created a multiple linear regression pricing model in R, resulting in improved pricing strategies for a client’s business.
    + Developed interactive dashboards using Power BI, SAP Analytics Cloud, and BrightGauge to visualize key performance indicators and track business metrics.
* **Production Coordinator**, [91.9 KCSB-FM in Santa Barbara](https://kcsb.org), Nov 2017 - June 2018
    + Timely produced excellent public service announcements (PSAs) and event promotions conforming with FCC guidelines.
    + Organized and trained volunteers to create PSAs and event promotions.
* **Scientific Computing Data Intern**, [National Center of Ecological Analysis and Synthesis](https://www.nceas.ucsb.edu/), Sep 2016 - Sep 2017
    + Maintained metadata for an NSF-funded data repository, ensuring accurate documentation and efficient data retrieval processes.
    + Conducted comprehensive data cleaning and pre-processing tasks on large and small datasets using R, ensuring data quality for analysis.
    + Facilitated knowledge sharing within the team by providing training and support on efficient programming techniques in R.
* **Business & Financial Planning Assistant**, [UCSB Housing, Dining & Auxiliary Enterprises](https://www.housing.ucsb.edu/home), May 2016 - Sep 2016
    + Efficiently memorized reports, wrote checks, tracked spending and prepared documentation.
    + Noted areas where the department was overspending, resulting in savings.

## Volunteer Experience
* **Radio Programmer**, [91.9 KCSB-FM in Santa Barbara](https://kcsb.org/), Jun 2017 - Jun 2018
    + Ran a weekly college radio music show called 'The Company of Lazarus'.
    + Operated a radio control board.
* **Secretary**, [oSTEM Inc. @ UC Santa Barbara](https://orgsync.com/66953/chapter), May 2016 - Apr 2017
    + Reaching out to STEM majors who are part of the LGBTQ community.
    + Educating on the importance of LGBTQ visibility and inclusivity.
* **Student Mentor**, Isla Vista Elementary, Sep 2016 - Jun 2017
    + Acted as a mentor and role model for a 6th grade student for a year.
* **Panelist**, UCSB Mental Health Conference, 2016, 2017
    + Took part on a panel to share personal experiences related to mental illness and advise on how to cope and intervene.
* **Peer Volunteer**, [Life of the Party](https://lifeoftheparty.sa.ucsb.edu/), UCSB Alcohol & Drug Program, Jan 2016 - May 2016
    + Encouraging the use of safer partying practices in Isla Vista, California.
    + Collaborated for a campus-wide “Be Safe and Pace” awareness campaign.
